### ISSUE TITLE
Enable markdown linter for each PR opened

### ISSUE THREAD

**Issue by ryankwilliams** [CSPI-QE/ocp-ci-docs#2]
To ensure new content added to the documentation is formatted properly, a GitHub action should be created to run markdown linter to validate the changes against the supported [rules](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md).

[Markdownlint](https://github.com/DavidAnson/markdownlint) is a good linter for markdown files. It has a cli package [markdownlint-cli2](https://github.com/DavidAnson/markdownlint-cli2) available to use from your laptop, integration with [GitHub Actions](https://github.com/marketplace/actions/markdownlint-cli2-action) and extensions for various IDEs ([vscode](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) as an example).

I have used the previous CLI/GitHub Action ([markdownlint-cli](https://github.com/igorshubovych/markdownlint-cli)) but looks like the cli2 is the one trying to be pushed more. Details about the differences can be found [here](https://dlaa.me/blog/post/markdownlintcli2).

I would suggest trying to stick to the default rules as much as possible. If there are exceptions, then those rules can be modified in the markdown lint config files.

**Comment by calebevans** [comment]
Working on this in a new PR.
